[package]
name = "cce-files"
version = "0.1.0"
edition = "2024"

[dependencies]
cce-ui = { path = "../cce-ui" }
wayland-client = { version = "0.31", features = ["system"] }
wgpu = "24"
bytemuck = { version = "1", features = ["derive"] }
glyphon = "0.8"
calloop = "0.13.0"
chrono = "0.4.44"
tokio = { version = "1", features = ["full"] }
notify = "8.2.0"
image = { version = "0.25.10", features = ["png", "jpeg"] }
log = "0.4"
kdl = "6.7.1"



[lib]
name = "cce_files"
path = "src/lib.rs"

[[bin]]
name = "cce-files"
path = "src/main.rs"
